F_W: exact_trips.c defines.h exact_network.c shortest_path.c links_used.c find_flows.c find_times.c alpha_find.c test.c F_W.c
	gcc -Wall -o F_W exact_trips.c exact_network.c shortest_path.c links_used.c find_flows.c find_times.c alpha_find.c test.c F_W.c -lm -g
